version: '3'

services:
  db:
    image: postgres:10.12-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-catalogodroids}
      - POSTGRES_USER=${POSTGRES_USER:-catalogodroids}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-catalogodroids@123}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: ./docker/entrypoint.web.sh
    env_file:
      - POSTGRES_DB=${POSTGRES_DB:-catalogodroids}
      - POSTGRES_USER=${POSTGRES_USER:-catalogodroids}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-catalogodroids@123}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
    ports:
      - "8000:8000"
    depends_on:
      - db
