# Generated by Django 3.1.2 on 2020-10-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda_pecas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandapeca',
            name='status_finalizacao',
        ),
        migrations.AddField(
            model_name='demandapeca',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
